[package]
name = "ft-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
azalea = "=0.16.0+mc26.1"
teloxide = { version = "0.13", features = ["macros"] }
tokio = { version = "1.49", features = ["full"] }
parking_lot = "0.12"
eyre = "0.6"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
